### PR TITLE
Fix fetching error of the HLTB

### LINKED ISSUE #142: [BUG]Error encountered when updating database from HTLB
Every time I run depressurizer, it pops up two warning windows.

I don't know if HLTB is howlongtobeat.com which I can visit.

There is also a issue on the Edit Profile window. The "?" appears in the wrong position.

Program Version: 4.10.0.0
OS: WIN10

### LINKED ISSUE #183: [BUG] [4.12.1] parsing issue
Hello,

When I launch the Depressurizer, I always get the following message.

error
Error encountered when updating database from HLTB: After parsing a value an unexpected character was encountered: A. Path 'Games[158].SteamAppData.SteamName', line 1, position xxxxx.

I am wondering how I can handle with this issue.

### PR DESCRIPTION
**Pull request by d3m3vilurr**
this data has unicode data in the `SteamName` and WebClient fetching
result would be broken.

here is a sample data (`result.Substring(61600, 30)`)
before:
`p Officer CG ?쏾huge Liang??與ゅ굇`

after:
` CG “Zhuge Liang” 横山光輝「三国志」タイア`

Resolve #142
Resolve #183

### CODE REVIEW

File: src/Depressurizer/Database.cs [hunk 1]
```diff
@@ -732,6 +732,7 @@ public int UpdateFromHLTB(bool includeImputedTimes)
 
             using (WebClient client = new WebClient())
             {
+                client.Encoding = System.Text.Encoding.UTF8;
```
Comment (mvegter) [inline src/Depressurizer/Database.cs]: Would you mind changing it to the following, this way it is consistent in the code base.
```suggestion
                client.Encoding = Encoding.UTF8;
```

**Review by mvegter — CHANGES_REQUESTED** [review]

File: src/Depressurizer/Database.cs (hunk 1 above)
Comment (d3m3vilurr) [reply src/Depressurizer/Database.cs]: done

**Review by mvegter — APPROVED** [review]
LGTM!

**Comment by AnnanFay** [comment]
Is it worth downloading the project and trying to compile it to get this fix?

If there's a release soon I'll just wait. Though as I just starting using the program I'm not sure what the bug is even effecting. I guess it's the "&#60;Unknown&#62;" column values?

**Comment by d3m3vilurr** [comment]
[Depressurizer.zip](https://github.com/Depressurizer/Depressurizer/files/5949628/Depressurizer.zip)
here is my build. but it also contains #192 patch.

**Comment by AnnanFay** [comment]
@d3m3vilurr Thanks, works great 🙂
